### ISSUE TITLE
Balances Don't Update On Network Change

### ISSUE THREAD

**Issue by dOrgJelli** [PrimeDAO/dapp-boilerplate-angular-bootstrap#1]
If a user changes their network within Metamask, the balances on the balance page do not update. A hard refresh is required via navigation or browser refresh.

**Comment by emoon-dev** [comment]
This actually turns out to be more complicated than one might think. See the ethers commentary in this thread https://github.com/ethers-io/ethers.js/issues/589 with extensive notes from @ricmoo and @danfinley.  The basics for network change detection is in the dapp template and someone who wanted to provide robust support for other networks could do so. Resolving this as won't fix as it is beyond the scope of this boilerplate template.
